// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/school-management/AdminDashboard.tsx": () => import("../components/mockups/school-management/AdminDashboard.tsx"),
  "./components/mockups/school-management/AttendanceTracker.tsx": () => import("../components/mockups/school-management/AttendanceTracker.tsx"),
  "./components/mockups/school-management/ClassSchedule.tsx": () => import("../components/mockups/school-management/ClassSchedule.tsx"),
  "./components/mockups/school-management/Gradebook.tsx": () => import("../components/mockups/school-management/Gradebook.tsx"),
  "./components/mockups/school-management/Notifications.tsx": () => import("../components/mockups/school-management/Notifications.tsx"),
  "./components/mockups/school-management/StudentProfile.tsx": () => import("../components/mockups/school-management/StudentProfile.tsx")
};
